spring.application.name=MediCareManagementSystem

spring.datasource.driver-class=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Mydb
spring.datasource.username=postgres
spring.datasource.password=2002


# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
